# -*- coding: utf-8 -*-
"""DeployJudolGuard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zU1Wnlj5n-uvZqmQMCiZQKEELkeEQpgC
"""
import streamlit as st
import plotly.express as px  

import os

AZURE_KEY      = "C0SG9EyACffSlTnabV0ClNFyn2FGD1rb0yoHkEMHtmQuO91l7Wm8JQQJ99CDACNns7RXJ3w3AAABACOGl0AL"          # ← Paste API Key Azure kamu
AZURE_ENDPOINT = "https://projekjudol.openai.azure.com/"
AZURE_DEPLOY   = "gpt-4o"

import streamlit as st

# Pakai st.secrets, jangan pakai os.environ atau file manual
AZURE_KEY = st.secrets["AZURE_KEY"]
AZURE_ENDPOINT = st.secrets["AZURE_ENDPOINT"]
AZURE_DEPLOY = st.secrets["AZURE_DEPLOY"]

if AZURE_KEY and AZURE_ENDPOINT:
    print(f"✓ Azure credentials siap")
    print(f"  Endpoint : {AZURE_ENDPOINT}")
    print(f"  API Key  : {AZURE_KEY[:8]}...{AZURE_KEY[-4:]} (masked)")
else:
    print("⚠️  Azure credentials kosong — dashboard tetap jalan, tombol AI pakai fallback statis")

import os

AZURE_KEY = "C0SG9EyACffSlTnabV0ClNFyn2FGD1rb0yoHkEMHtmQuO91l7Wm8JQQJ99CDACNns7RXJ3w3AAABACOGl0AL"
AZURE_ENDPOINT = "https://projekjudol.openai.azure.com/"
AZURE_DEPLOY = "gpt-4o"

print(f"✓ {secrets_path} created with Azure credentials.")

import os

print("Cek file yang dibutuhkan:")
required = {
    '06_dashboard.py'                          : 'File dashboard',
    'risk_scores_with_explanation.csv'    : 'Risk scores + GPT explanation',
    'judolguard_.csv'             : 'Features dataset',
    'model_metrics.txt'                   : 'Model metrics',
    'eda_behavioral_shift.png'            : 'EDA chart',
    'xgb_judolguard.pkl'                : 'Trained model',
}
all_ok = True
for path, desc in required.items():
    ok = os.path.exists(path)
    if not ok: all_ok = False
    print(f"  {'✓' if ok else '✗ MISSING'} {path}  ({desc})")

if not all_ok:
    print("\n⚠️  Ada file yang missing. Jalankan notebook sebelumnya dulu.")
else:
    print("\n✓ Semua file siap. Lanjut ke Cell 3 untuk deploy.")

import os
print("Working directory:", os.getcwd())
print("\nIsi folder data/:")
os.makedirs('data', exist_ok=True)
print(os.listdir('data'))

import os
os.makedirs('data', exist_ok=True)
os.makedirs('models', exist_ok=True)

# Pindahkan ke folder data/
import shutil
for fname in uploaded.keys():
    shutil.move(fname, f'data/{fname}')
    print(f"✓ {fname} dipindah ke data/")

import pandas as pd
import numpy as np
import joblib
from sklearn.ensemble import IsolationForest
import xgboost as xgb
from sklearn.model_selection import train_test_split

# Load data
df = pd.read_csv('/content/data/judolguard.csv')

FEATURE_COLS = [
    'hour_of_day', 'is_night', 'night_ratio_7d', 'night_ratio_14d', 'temporal_shift',
    'amount_log', 'amount_vs_avg_7d', 'total_amount_7d',
    'tx_count_24h', 'tx_count_7d', 'burst_score',
    'unique_recv_7d', 'unique_recv_24h', 'qris_ratio_7d',
    'drain_cycle_flag', 'dormant_flag'
]

X = df[FEATURE_COLS].fillna(0)
y = df['is_at_risk']

# Isolation Forest
iso = IsolationForest(n_estimators=200, contamination=0.35, random_state=42)
iso.fit(X[y==0])
raw = iso.score_samples(X)
df['anomaly_score'] = 1 - ((raw - raw.min()) / (raw.max() - raw.min()))

X['anomaly_score'] = df['anomaly_score']

# XGBoost
spw = len(y[y==0]) / len(y[y==1])
xgb_model = xgb.XGBClassifier(
    n_estimators=300, max_depth=6, learning_rate=0.05,
    scale_pos_weight=spw, random_state=42, n_jobs=-1,
    eval_metric='aucpr', use_label_encoder=False
)
xgb_model.fit(X, y, verbose=False)

# Risk scores per akun
df['risk_prob']  = xgb_model.predict_proba(X)[:, 1]
df['risk_score'] = (df['risk_prob'] * 100).round(1)

def get_level(s):
    if s <= 30: return 'Low'
    elif s <= 60: return 'Medium'
    elif s <= 80: return 'High'
    else: return 'Critical'

def get_rec(l):
    return {
        'Low'     : 'Monitor pasif — tidak ada tindakan segera',
        'Medium'  : 'Kirim notifikasi edukasi ke nasabah',
        'High'    : 'Batasi nominal transfer harian, minta konfirmasi',
        'Critical': 'Eskalasi ke tim compliance & flag ke OJK'
    }[l]

def get_trigger(row):
    triggers = {
        'Aktivitas malam tinggi' : row['avg_night_ratio'],
        'Frekuensi tinggi'       : row['avg_tx_24h'] / 20,
        'Banyak penerima'        : row['avg_unique_recv'] / 10,
        'Velocity burst'         : row['avg_burst_score'] / 5,
        'Pergeseran ke malam'    : max(row['avg_temporal_shift'], 0),
        'Penggunaan QRIS tinggi' : row['avg_qris_ratio'],
    }
    top = sorted(triggers.items(), key=lambda x: x[1], reverse=True)[:2]
    return ' & '.join([t[0] for t in top])

risk = df.groupby('account_id').agg(
    risk_score_max       = ('risk_score', 'max'),
    profile              = ('profile', 'first'),
    is_at_risk_true      = ('is_at_risk', 'first'),
    n_transactions       = ('step', 'count'),
    avg_night_ratio      = ('night_ratio_7d', 'mean'),
    avg_tx_24h           = ('tx_count_24h', 'mean'),
    avg_unique_recv      = ('unique_recv_7d', 'mean'),
    avg_burst_score      = ('burst_score', 'mean'),
    avg_temporal_shift   = ('temporal_shift', 'mean'),
    avg_qris_ratio       = ('qris_ratio_7d', 'mean'),
).reset_index()

risk['final_risk_score'] = risk['risk_score_max'].round(1)
risk['risk_level']       = risk['final_risk_score'].apply(get_level)
risk['recommendation']   = risk['risk_level'].apply(get_rec)
risk['top_triggers']     = risk.apply(get_trigger, axis=1)
risk['explanation']      = 'Penjelasan belum di-generate.'

risk.to_csv('data/risk_scores.csv', index=False)
risk.to_csv('data/risk_scores_with_explanation.csv', index=False)

import os; os.makedirs('models', exist_ok=True)
joblib.dump(xgb_model, 'models/xgb_judolguard.pkl')

print(f"✓ risk_scores.csv tersimpan: {len(risk)} akun")
print(f"✓ Distribusi:\n{risk['risk_level'].value_counts().to_string()}")

import os
from openai import AzureOpenAI

# Initialize the Azure OpenAI client
client = AzureOpenAI(
    api_key=os.environ.get("AZURE_KEY"),
    azure_endpoint=os.environ.get("AZURE_ENDPOINT"),
    api_version="2024-02-01"
)

# Test a simple chat completion call
try:
    response = client.chat.completions.create(
        model=os.environ.get("AZURE_DEPLOY"), # deployment name
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Hello, what is your name?"}
        ]
    )
    print("Azure OpenAI connection successful!")
    print("Response:", response.choices[0].message.content)
except Exception as e:
    print(f"Azure OpenAI connection failed: {e}")
